ci: remove node 14 from build, adds node 20

diff --git a/.github/workflows/node.js.yml b/.github/workflows/node.js.yml
--- a/.github/workflows/node.js.yml
+++ b/.github/workflows/node.js.yml
@@ -10,46 +10,46 @@ name: Node.js CI
 
 on:
   push:
-    branches: [ main ]
+    branches: [main]
   pull_request:
-    branches: [ main ]
+    branches: [main]
   workflow_dispatch:
-  
+
 jobs:
   build:
     runs-on: ubuntu-latest
 
     strategy:
       matrix:
-        node-version: [14.x, 16.x, 18.x]
+        node-version: [16.x, 18.x, 20.x]
 
     steps:
-    - uses: actions/checkout@v3
-    - name: Use Node.js ${{ matrix.node-version }}
-      uses: actions/setup-node@v1
-      with:
-        node-version: ${{ matrix.node-version }}
-    - run: npm ci
-    - run: npm run lint
-      if: ${{ matrix.node-version == '16.x' }}
-    - run: npm run compile --if-present
-    - run: npm test
-    - name: Test Report
-      uses: dorny/test-reporter@v1
-      if: success() || failure()    # run this step even if previous step failed
-      continue-on-error: true
-      with:
-        name: JEST Tests      # Name of the check run which will be created
-        path: junit.xml       # Path to test results
-        reporter: jest-junit  # Format of test results
-        fail-on-error: 'false'
-    - uses: codecov/codecov-action@894ff025c7b54547a9a2a1e9f228beae737ad3c2 # v3.1.3
-      name: Upload Coverage Results
-      if: ${{ matrix.node-version == '16.x' }}
-    - name: Rename test file
-      run: mv junit.xml mps-unit.xml
-    - name: Upload JEST Results
-      uses: actions/upload-artifact@v3
-      with:
-        name: mps-unit
-        path: mps-unit.xml
+      - uses: actions/checkout@v3
+      - name: Use Node.js ${{ matrix.node-version }}
+        uses: actions/setup-node@v1
+        with:
+          node-version: ${{ matrix.node-version }}
+      - run: npm ci
+      - run: npm run lint
+        if: ${{ matrix.node-version == '18.x' }}
+      - run: npm run compile --if-present
+      - run: npm test
+      - name: Test Report
+        uses: dorny/test-reporter@v1
+        if: success() || failure() # run this step even if previous step failed
+        continue-on-error: true
+        with:
+          name: JEST Tests # Name of the check run which will be created
+          path: junit.xml # Path to test results
+          reporter: jest-junit # Format of test results
+          fail-on-error: "false"
+      - uses: codecov/codecov-action@894ff025c7b54547a9a2a1e9f228beae737ad3c2 # v3.1.3
+        name: Upload Coverage Results
+        if: ${{ matrix.node-version == '18.x' }}
+      - name: Rename test file
+        run: mv junit.xml mps-unit.xml
+      - name: Upload JEST Results
+        uses: actions/upload-artifact@v3
+        with:
+          name: mps-unit
+          path: mps-unit.xml
